repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
        name: Check YAML
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
    -   id: markdownlint
        name: Check Markdownlint
-   repo: https://github.com/jonasbn/pre-commit-hooks
    rev: v0.3.0
    hooks:
    -   id: prohibit-commit-main
-   repo: https://github.com/henryykt/pre-commit-perl
    rev: v0.0.4
    hooks:
    -   id: perlcritic
    -   id: perltidy
