sudo: false
language: perl
perl:
- '5.24'
- '5.22'
- '5.20'
- '5.10'
before_install:
- git config --global user.name "TravisCI"
install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- cpanm --quiet --notest Test::Kwalitee
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest Dist::Zilla::App::Command::cover
- dzil authordeps --cpanm-versions | perl -p -e 's/"//g' | cpanm --quiet --notest
  --skip-satisfied
- dzil listdeps --cpanm-versions | perl -p -e 's/"//g' | cpanm --quiet
- export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c
  HARNESS_TIMER=1
script:
- dzil smoke --release --author
after_success:
- dzil cover -outputdir cover_db -report coveralls
notifications:
  slack:
    secure: XcJLvDiuw5Kk8coWOoXA/37zPrURHi9GD64c3+AiBI0TccBtKakCNk4iKzxLjr656SrBsUeDn5RVmLEUYroVDnpjdZumv4OTc/TV+y8O6G1N1f1DAjFhgjKg3T2G09O/OROEMzsfCW+sON5L18Hi8C2YKBg0dKSClr7XERNIvsM=
